//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantuarioUM.Resources.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SantuarioUM.Resources.Languages.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DashTileText {
            get {
                return ResourceManager.GetString("DashTileText", resourceCulture);
            }
        }
        
        internal static string FurnituresText {
            get {
                return ResourceManager.GetString("FurnituresText", resourceCulture);
            }
        }
        
        internal static string BibleVersesText {
            get {
                return ResourceManager.GetString("BibleVersesText", resourceCulture);
            }
        }
        
        internal static string RitualText {
            get {
                return ResourceManager.GetString("RitualText", resourceCulture);
            }
        }
        
        internal static string FulfilmentText {
            get {
                return ResourceManager.GetString("FulfilmentText", resourceCulture);
            }
        }
        
        internal static string ApplicationText {
            get {
                return ResourceManager.GetString("ApplicationText", resourceCulture);
            }
        }
    }
}
